# Generated by Django 4.0.3 on 2022-03-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Debito'), (2, 'Boleto'), (3, 'Financiamento'), (4, 'Credito'), (5, 'Recebimento Emprestimo'), (6, 'Vendas'), (7, 'Recebimento Ted'), (8, 'Recebimento Doc'), (9, 'Aluguel')])),
                ('description', models.CharField(max_length=60)),
                ('nature', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=8)),
                ('sign', models.CharField(choices=[('+', 'Plus'), ('-', 'Minus')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('value', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('hour', models.CharField(max_length=6)),
                ('shop_owner', models.CharField(max_length=14)),
                ('shop_name', models.CharField(max_length=19)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnab.transaction')),
            ],
        ),
    ]
